apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: agentic-net-gateway
spec:
  gatewayClassName: cloud-provider-kind
  listeners:
    - protocol: HTTP
      port: 10001
      name: agentic-net-gateway-listener1
      allowedRoutes:
        namespaces:
          from: Same
