/*
Copyright 2025 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
	agenticv1alpha1 "sigs.k8s.io/kube-agentic-networking/api/agentic/v1alpha1"
)

// AuthPolicyLister helps list AuthPolicies.
// All objects returned here must be treated as read-only.
type AuthPolicyLister interface {
	// List lists all AuthPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*agenticv1alpha1.AuthPolicy, err error)
	// AuthPolicies returns an object that can list and get AuthPolicies.
	AuthPolicies(namespace string) AuthPolicyNamespaceLister
	AuthPolicyListerExpansion
}

// authPolicyLister implements the AuthPolicyLister interface.
type authPolicyLister struct {
	listers.ResourceIndexer[*agenticv1alpha1.AuthPolicy]
}

// NewAuthPolicyLister returns a new AuthPolicyLister.
func NewAuthPolicyLister(indexer cache.Indexer) AuthPolicyLister {
	return &authPolicyLister{listers.New[*agenticv1alpha1.AuthPolicy](indexer, agenticv1alpha1.Resource("authpolicy"))}
}

// AuthPolicies returns an object that can list and get AuthPolicies.
func (s *authPolicyLister) AuthPolicies(namespace string) AuthPolicyNamespaceLister {
	return authPolicyNamespaceLister{listers.NewNamespaced[*agenticv1alpha1.AuthPolicy](s.ResourceIndexer, namespace)}
}

// AuthPolicyNamespaceLister helps list and get AuthPolicies.
// All objects returned here must be treated as read-only.
type AuthPolicyNamespaceLister interface {
	// List lists all AuthPolicies in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*agenticv1alpha1.AuthPolicy, err error)
	// Get retrieves the AuthPolicy from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*agenticv1alpha1.AuthPolicy, error)
	AuthPolicyNamespaceListerExpansion
}

// authPolicyNamespaceLister implements the AuthPolicyNamespaceLister
// interface.
type authPolicyNamespaceLister struct {
	listers.ResourceIndexer[*agenticv1alpha1.AuthPolicy]
}
