/*
Copyright 2025 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	apiagenticv1alpha1 "sigs.k8s.io/kube-agentic-networking/api/agentic/v1alpha1"
	versioned "sigs.k8s.io/kube-agentic-networking/k8s/client/clientset/versioned"
	internalinterfaces "sigs.k8s.io/kube-agentic-networking/k8s/client/informers/externalversions/internalinterfaces"
	agenticv1alpha1 "sigs.k8s.io/kube-agentic-networking/k8s/client/listers/agentic/v1alpha1"
)

// AuthPolicyInformer provides access to a shared informer and lister for
// AuthPolicies.
type AuthPolicyInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() agenticv1alpha1.AuthPolicyLister
}

type authPolicyInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewAuthPolicyInformer constructs a new informer for AuthPolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewAuthPolicyInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredAuthPolicyInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredAuthPolicyInformer constructs a new informer for AuthPolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAuthPolicyInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AgenticV1alpha1().AuthPolicies(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AgenticV1alpha1().AuthPolicies(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AgenticV1alpha1().AuthPolicies(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AgenticV1alpha1().AuthPolicies(namespace).Watch(ctx, options)
			},
		},
		&apiagenticv1alpha1.AuthPolicy{},
		resyncPeriod,
		indexers,
	)
}

func (f *authPolicyInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredAuthPolicyInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *authPolicyInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apiagenticv1alpha1.AuthPolicy{}, f.defaultInformer)
}

func (f *authPolicyInformer) Lister() agenticv1alpha1.AuthPolicyLister {
	return agenticv1alpha1.NewAuthPolicyLister(f.Informer().GetIndexer())
}
